apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: lab-clustersecretstore # Name of the ClusterSecretStore
spec:
  provider:
    aws:
      service: ParameterStore # Determines which External Secrets to use, in our case it's Amazon Parameter Store
      region: us-east-1