apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lab-eso-config-es
spec:
  dataFrom:
  - find:
      path: /eso/lab/     # From which path do I read the variables in Parameter Store? From the path /test/
      name:
        regexp: ".*"   # What exactely do I read? Everything after the path mentioned above
    rewrite: 
      - regexp:   # This section removes some extra characters and maps Parameters to the Secret
          source: "^/eso/lab/"
          target: ""

  refreshInterval: 300s   # Interval when ParameterStore and created Secret will be synced (if some change occured)
  secretStoreRef:
    kind: ClusterSecretStore
    name: lab-clustersecretstore   # Name of the ClusterSecretStore object to associate with
  target:
    creationPolicy: Owner
    deletionPolicy: Delete   # Determines what will happen to the Secret if ExternalSecret object is deleted - Delete and Retain are possible values
    name: eso-config   # The name of the secret that will be created